# Generated by Django 3.2.9 on 2022-01-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_livros_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='resume',
            field=models.TextField(default='', max_length=500),
        ),
    ]
